spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver # MariaDB? Mysql ?? ??? ???? ????? ???? ??.
    url: jdbc:mariadb://localhost:3306/exam_db # Docker?? Mysql? ???? ??, ???? DBeaver? MariaDb???? ??? ??.
    username: root
    password: riskmgt951753@
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        transaction:
          jta:
            platform: org.hibernate.service.jta.JtaPlatform # JTA ??? ?? ??