spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mariadb://localhost:3306/exam_db
    username: root
    password: riskmgt951753@
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    p6spy: info
